
server:
  port: 8100
spring:
  redis:
      host: xxxx
      port: 6379
      password: xxx
      database: 0
      pool:
          max-active: 50
          maxTotal: 50
          max-idle: 10
          min-idle: 3
          max-wait: -1
          testWhileIdle: true
          minEvictableIdleTimeMillis: 60000
          timeBetweenEvictionRunsMillis: 30000
          numTestsPerEvictionRun: 3
      timeout: 1000
logging:
    level:
      per.lx: DEBUG
